- src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapper.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/utils/MappingRulesLoader.java
Trivial PR to fix some IDE warnings.
> Fixed some IDE warnings

- pom.xml
- src/test/java/io/strimzi/kafka/bridge/mqtt/core/utils/MappingRulesLoaderTest.java
> Used mockito to test MappingRulesLoader

- src/test/java/io/strimzi/kafka/bridge/mqtt/core/ConfigRetrieverTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/core/utils/MappingRulesLoaderTest.java
> Added copyright and removed wildcard imports.

- src/main/java/io/strimzi/kafka/bridge/mqtt/config/MqttConfig.java
> fixed wrong prefix for the MQTT port and host

- src/main/java/io/strimzi/kafka/bridge/mqtt/config/BridgeConfig.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/config/KafkaConfig.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/config/KafkaProducerConfig.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/config/MqttConfig.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MappingRule.java
Trivial PR to fix some wrong formatted `toString()` methods.
> Fixed some toString() methods

- README.md
Trivial PR to add the Azure pipeline badge to the landing page.
> Added Azure pipeline badge

- src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
Trivial PR to print the MQTT clientid on connection and a little refactoring around handling the publish message.
> Added logging MQTT clientid on connection and publish refactoring

- pom.xml
- src/test/java/io/strimzi/kafka/bridge/mqtt/core/ConfigRetrieverTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/kafka/KafkaBridgeProducerTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MappingRulesLoaderTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaRegexMapperTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaSimpleMapperTest.java
Trivial PR to migrate from Junit 4 to Junit 5.
> chore: migrate from Junit 4 to Junit 5

- README.md
Trivial PR to fix some issues with the docs.
> docs: adjusted markdowns and a confusing phrase.

- bin/mqtt_bridge_run.sh
Trivial PR to add the missing $ in exec command in bin/mqtt_bridge_run.sh
> added a missing $ in bin/mqtt_bridge_run.sh

- .azure/build-pipeline.yaml
- .azure/scripts/container-build.sh
- .azure/scripts/container-push.sh
- .azure/templates/jobs/build_container.yaml
- .azure/templates/jobs/build_java.yaml
- .azure/templates/jobs/push_container.yaml
- .azure/templates/steps/setup_docker.yaml
This PR updates the current build pipeline in order to add build and push container.
> Updated Azure build pipeline to build and push container

- README.md
- config/application.properties
- src/main/java/io/strimzi/kafka/bridge/mqtt/config/BridgeConfig.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServer.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerInitializer.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapper.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaRegexMapper.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaSimpleMapper.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/config/ConfigRetrieverTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/config/ConfigTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaRegexMapperTest.java
- src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaSimpleMapperTest.java
- src/test/resources/application.properties
> feat: allow the user to set a default Kafka topic for the bridge

- development-docs/RELEASING.md
This trivial PR adds some documentation about how to deal with releasing.
It's mostly taken from the Strimzi Kafka Bridge documentation.
> Added RELEASING documentation

- README.md
Trivial PR with some additions/changes on the README.
> Some additions on the README

- README.md
This PR updates the instructions for running the bridge on bare metal and Kubernetes.
> Updated README with running methods

- README.md
Trivial PR to add a Contributing section to the README.
> Added Contributing section to the README

- BUILDING.md
- README.md
Trivial PR to add the BUILDING guide.
> Added BUILDING guide

- install/000-ServiceAccount.yaml
- install/010-Service.yaml
- install/020-ConfigMap.yaml
- install/030-Deployment.yaml
This trivial PR adds the `install` folder with 0.1.0 release.
> Added install folder with 0.1.0 release

- pom.xml
Bumped some dependencies to align with other Strimzi components.
> Bumped some dependencies

- src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
- src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerInitializer.java
Trivial PR to add some missing Javadoc.
> Added Javadoc on some constructors

- pom.xml
Trivial PR to add all the maintainers missing on the pom file.
> Added all maintainers

- pom.xml
Trivial PR to bumped test container 0.110.0
> Bumped test container 0.110.0
