strimzi/strimzi-mqtt-bridge

src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MappingRule.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapper.java
src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapperTest.java

The mapping logic is not just "utils".
This PR moves the `MappingRule` in a new `mapper` package together with the `MqttKafkaMapper` itself.
They deserve a dedicated package.

Refactoring from utils to mapper package

---

README.md

This PR proposes the documentation for the MQTT bridge. It contains the following informations:
> How to run the Bridge
> How to use the Bridge
> How to configure the bridge.
Signed-off-by: Antonio Pedro <tonio.pedro99@gmail.com>

doc: add documentation

---

src/main/resources/log4j2.properties

Current log layout pattern is very bad by cutting classes and thread names. This PR uses the same layout from the Strimzi cluster operator.

Fix logging layout

---

src/main/java/io/strimzi/kafka/bridge/mqtt/Main.java
src/test/java/io/strimzi/kafka/bridge/mqtt/core/ConfigRetrieverTest.java

This trivial PR makes the configuration file command line parameter as mandatory as we don't want user to run the bridge with a built in configuration y default which could not work for them. Let's follow the same Strimzi HTTP bridge approach.
This also fix a config related test which is anyway not related to the above change.

Make the --config-file mandatory and fix config related test

---

Makefile
Makefile.maven
Makefile.os

This PR adds Makefile(s) just for running a Java build. No Docker included, no spotbugs and so on.
We'll add more as they come.
This is an initial step to use them in the upcoming Azure pipeline for the project mostly to build and run tests.

Added initial Makefile(s)

---

pom.xml

Trivial PR to bump Jackson deps to 2.15.2 to avoid potential vulnerabilities and align with latest update in the Strimzi operator https://github.com/strimzi/strimzi-kafka-operator/pull/8856 and HTTP bridge https://github.com/strimzi/strimzi-kafka-bridge/pull/822

Bumped Jackson to 2.15.2

---

README.md
src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MappingResult.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MappingRule.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapper.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaRegexMapper.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaSimpleMapper.java
src/test/java/io/strimzi/kafka/bridge/mqtt/core/utils/MappingRulesLoaderTest.java
src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapperTest.java
src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaRegexMapperTest.java
src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaSimpleMapperTest.java
src/test/resources/mapping-rules-regex.json
src/test/resources/mapping-rules.json

This PR includes:
- Added `kafkaKey` in the Topic Mapping Rules (this will fix #20).
- New way to define MQTT topic pattern: Now users can use regex as MQTT patterns, and gives the user more possibility to define rules.
- Placeholders are no longer defined as `{placeholder}`: Now we are using positional placeholders like $1, which means, get the value of the first capturing group in the MQTT pattern.
- The MqttKafkaMapper.map(String) does not return a String: Now the result of the mapping consists of a Kafka Topic and a Kafka record key, and they are wrapped in an object of a class called `MappingResult`.
-Tests for the new Mapper.
- Updated docs.

feat: added a new MqttKafkaMapper and updated docs.

---

src/main/java/io/strimzi/kafka/bridge/mqtt/Main.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
src/main/java/io/strimzi/kafka/bridge/mqtt/kafka/KafkaBridgeProducer.java
src/main/java/io/strimzi/kafka/bridge/mqtt/kafka/KafkaProducerAckLevel.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MappingRulesLoader.java
src/test/java/io/strimzi/kafka/bridge/mqtt/mapper/MappingRulesLoaderTest.java

This PR moves some classes out of the `utils` package because they can't be considered "just" utils.
The `KafkaProducerAckLevel` was moved into `kafka` package because it's actual part of the Kafka producer logic.
The `MappingRulesLoader` was moved into `mapper` package bacause it's the main piece loading the mapping rules.

Moved classes out of utils

---

pom.xml

It seems that the addition of the test-container dependency (bringing an implicit failsafe plugin configuration) breaks tests which don't run anymore.
This PR adds usage of Failsafe plugin (for integration tests) and Surefire pluging (for unit tests) explicitely fixing this issue.

Added Surefire and Failsafe plugins for running tests

---

src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
src/test/java/io/strimzi/kafka/bridge/mqtt/MqttBridgetIT.java

This trivial PR adds the published MQTT topic to the produced Kafka record header so the Kafka consumer can get where the message was published.

Add the published MQTT topic in the produced Kafka record header

---

README.md
config/application.properties
install/020-ConfigMap.yaml
src/main/java/io/strimzi/kafka/bridge/mqtt/config/MqttConfig.java
src/test/java/io/strimzi/kafka/bridge/mqtt/config/ConfigTest.java
src/test/resources/application.properties

This PR removes the `server` prefix for MQTT host and port to stick with the same pattern we have with the current Strimzi HTTP bridge.
It's anyway clear what's the purpose of host and port, it could be server only because the bridge doesn't have any client part.

Refactor MQTT host and port properties

---

.spotbugs/spotbugs-exclude.xml
pom.xml
src/main/java/io/strimzi/kafka/bridge/mqtt/Main.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaMapper.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaRegexMapper.java
src/main/java/io/strimzi/kafka/bridge/mqtt/mapper/MqttKafkaSimpleMapper.java

This PR adds spotbugs and also makes some changes on the Java code.
These changes are related to the following warnings raised by spotbugs:
```shell
[INFO] Total bugs: 6
[ERROR] Low: Exception is caught when Exception is not thrown in io.strimzi.kafka.bridge.mqtt.Main.main(String[]) [io.strimzi.kafka.bridge.mqtt.Main] At Main.java:[line 67] REC_CATCH_EXCEPTION
[ERROR] Low: Unchecked/unconfirmed cast from io.netty.handler.codec.mqtt.MqttMessage to io.netty.handler.codec.mqtt.MqttConnectMessage in io.strimzi.kafka.bridge.mqtt.core.MqttServerHandler.channelRead0(ChannelHandlerContext, MqttMessage) [io.strimzi.kafka.bridge.mqtt.core.MqttServerHandler] At MqttServerHandler.java:[line 86] BC_UNCONFIRMED_CAST
[ERROR] Low: Unchecked/unconfirmed cast from io.netty.handler.codec.mqtt.MqttMessage to …
```

Added spotbugs

---

Makefile.maven

Trivial PR to add missing Makefile target for spotbugs which will be needed in the Azure pipeline.

Added missing spotbugs target in Makefile

---

CHANGELOG.md
pom.xml

This trivial PR adds CHANGELOG.
It also bumps Kafka to 3.6.1.

Added CHANGELOG

---

packaging/install/010-Service.yaml
packaging/install/020-ConfigMap.yaml
packaging/install/030-Deployment.yaml
pom.xml
src/main/java/io/strimzi/kafka/bridge/mqtt/Main.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/HttpServer.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/Liveness.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServer.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/Readiness.java

This PR fixes #64
It adds and HTTP server for handling liveness and readiness probes.

Add an HTTP server for liveness and readiness probes

---

Makefile

This PR fixes the release targets in the Makefile.
It was missing updating the Deployment file with the release version.
It's now more similar to the drain cleaner release process which provides installation files compared to the HTTP bridge which doesn't provide them.

Fixed release targets in Makefile

---

README.md
config/application.properties
src/test/java/io/strimzi/kafka/bridge/mqtt/MqttBridgetIT.java
src/test/java/io/strimzi/kafka/bridge/mqtt/config/ConfigRetrieverTest.java
src/test/resources/application.properties

This PR fixes the default MQTT host to be `0.0.0.0` instead of `localhost` in the configuration files, doc and tests.
It aligns with what we have with the HTTP bridge as well as avoid users mistakes to have it listening on 127.0.0.1 by default and then not able to send request to the actual IP (i.e. when using an Nginx proxy).

Set the default MQTT host as 0.0.0.0

---

pom.xml
src/main/java/io/strimzi/kafka/bridge/mqtt/Main.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/HttpServer.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServer.java
src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
src/test/java/io/strimzi/kafka/bridge/mqtt/MqttBridgetIT.java

As already done with the HTTP bridge https://github.com/strimzi/strimzi-kafka-bridge/pull/864, this PR moves from slf4j to log4j2 for our own loggers.

Use log4j2 instead of slf4j for our own loggers

---

src/main/java/io/strimzi/kafka/bridge/mqtt/config/KafkaConfig.java

Trivial PR to remove an unused constant related to bootstrap server which is get by filtering the `kafka.` prefixed configuration.

Removed unused constant

---

src/main/java/io/strimzi/kafka/bridge/mqtt/core/MqttServerHandler.java
src/test/java/io/strimzi/kafka/bridge/mqtt/MqttBridgetIT.java

This PR introduces a handler function for PingReq messages, which must be answered with a PingResp message.

Implement answer to PingReq MQTT messages (fixes #85)

---

pom.xml

Trivial PR to bump Kafka 4.0.0 and Netty 4.1.118.Final.

Bumped Kafka 4.0.0 and Netty 4.1.118.Final
